Issue 84
cancervariants/metakb pull request #142
Opened 2021-12-22 20:03 UTC by jsstevenson

2021-12-29 22:10 UTC, korikuzma reviewed
Few comments while I update my cdm files...

2021-12-29 22:10 UTC, korikuzma commented on metakb/schemas.py
> +Predicate = Union[PredictivePredicate, DiagnosticPredicate,
Should replace union in `Proposition` class as well with `Predicate`

2021-12-29 23:09 UTC, korikuzma requested changes
Please fix failing tests

2022-01-04 14:57 UTC, jsstevenson commented on analysis/civic/examples/transform/civic_cdm_20211228.json
> +            "proposition": "proposition:5k7StVvnNBf6qxTgXgZBCSaiyWScvS3Q",
Yeah, it feels a little weird, but hashing is the only way I can think of to make IDs consistent without some sort of "seed" (like an existing, populated database) that the transform methods perform lookups against (which also feels a little weird?

2022-01-18 19:57 UTC, jsstevenson commented
I'm going to close this for now -- I think we can make some progress given concurrent updates to the rest of MetaKB but we can return to it later

2022-01-25 23:48 UTC, jsstevenson commented
[@korikuzma I edited the PR description as well -- may spur thoughts]

2022-01-26 01:55 UTC, korikuzma requested changes
Haven't looked at this much, but read updated description + CLI changes. Have a couple comments:
- Could you merge staging + resolve conflicts before I take a deeper look?
- For the new CLI option, I would maybe use a better name like `load_new_cdm` + maybe even change `load_transformed` to `load_transformed_cdms`. I think this would help make the option names clearer that the former is loading a single CDM file and the latter is loading multiple CDM files.
- For your comment about loading from s3, that issue exists [here](https://github.com/cancervariants/metakb/issues/108).

2022-01-27 15:27 UTC, jsstevenson commented
I'm quickly realizing that a lot of the CLI options get sort of confusing between the MetaKB database and the normalizer tables

Maybe something like this (for this + #108)?

```
    @click.option(
        "--load_latest_cdms",
        "-l",
        is_flag=True,
        default=False,
        help=("Clear MetaKB database and load most recent available source CDM "
              "files. Does not run harvest and transform methods to generate "
              "new CDM files.")
    )
    @click.option(
        "--load_target_cdm",
        "-t",
        type=click.Path(exists=True, dir_okay=False, readable=True,
                        path_type=Path),
        required=False,
        help=("Load transformed CDM file at specified path. Overrides "
              "--load_normalizers_db, --force_load_normalizers_db, "
              "and --load_newest_cdms.")
    )
    @click.option(
        "--load_retrieved_cdms",
        "-r",
        default=False,
        help=("Retrieve latest CDM files from remote repository, then clear "
              "MetaKB database and load retrieved data. Overrides  "
              "--load_target_cdm, --load_normalizers_db, "
              "--force_load_normalizers_db, and --load_newest_cdms.")
    )
```

2022-01-27 15:30 UTC, korikuzma commented
> 

Could we do `load_s3_cdms` rather than `load_retrieved_cdms`?

2022-01-27 15:31 UTC, jsstevenson commented
Yeah, that makes sense to me

2022-01-27 23:01 UTC, korikuzma requested changes
Small changes. Going to re-run transforms while you address suggestions.

2022-01-27 23:15 UTC, korikuzma commented
@jsstevenson also need to update `cli.py`. `load_transformed` --> `load_latest_cdms` and `specify_transform_file` --> `load_target_cdm`. Currently it throws an error

2022-01-27 23:56 UTC, jsstevenson commented on analysis/civic/examples/transform/civic_cdm_20220111.json
> +            "id": "civic.eid:879",
Ah good call -- I believe I changed the civic example script to just save to a static name but there are some old ones hanging around

2022-01-28 13:58 UTC, korikuzma commented
@jsstevenson I'm still getting some failed tests. Some are due to me not updating my database (which I'm doing now), but I think others may not be due to this (might be wrong). Do any of your tests fail?

2022-02-02 14:24 UTC, korikuzma requested changes
Do you wanna go ahead and bump the variation-normalizer version in requirements? I'm getting that one pandas/sqlalchemy warning you were talking about a couple days ago

2022-02-03 13:20 UTC, korikuzma approved these changes

2022-02-03 17:02 UTC, merged