Issue 54
cancervariants/metakb pull request #58
Opened 2021-03-22 03:54 UTC by MayLiu27

Making a draft PR so the team can take a look now, and waiting to see if any changes need to be made for civic that also apply to MOA

2021-03-26 12:39 UTC, korikuzma commented on metakb/transform/moa.py
> +            gene_context=f"moa:{[g_des['id'] for g_des in g_descriptors]}",
This is causing the `gene_context` field to have brackets. You should get the first result or return None.

2021-03-29 13:06 UTC, korikuzma requested changes

2021-03-29 13:06 UTC, korikuzma commented on metakb/transform/moa.py
> +            if not descriptors:
This will always return `True` since `_get_descriptors` returns a tuple.

2021-03-29 13:06 UTC, korikuzma commented on metakb/transform/moa.py
> +    def _get_record(self, record_id, records):
We should consider creating a base class for redundant code between sources.

2021-03-29 13:18 UTC, MayLiu27 commented on metakb/schemas.py
> +    disease_descriptor: Optional[str]
I made them optional cuz there are disease and therapy which return match_type = 0 from normalizer

2021-03-29 13:20 UTC, MayLiu27 commented on metakb/transform/moa.py
> +        cdm_evidence_items = {}  # EIDs that have been transformed to CDM
I was making the name consistent since they all reflect to `evidence_items` content. I'll change them back to `assertions`

2021-03-29 13:22 UTC, korikuzma commented on metakb/schemas.py
> +    disease_descriptor: Optional[str]
If you look at line 97, you can see that if there isn't a disease or therapy descriptor, then we skip even adding the TR Proposition. So we can remove the optional and make them required.

2021-03-29 13:23 UTC, korikuzma commented on metakb/transform/moa.py
> +        cdm_evidence_items = {}  # EIDs that have been transformed to CDM
Ahhh okay. If you want to make them consistent, the term we use for Evidence/Evidence Line/Assertions is Statement.

2021-03-31 18:46 UTC, korikuzma approved these changes
Looks good!

2021-03-31 18:46 UTC, korikuzma commented on metakb/transform/moa.py
> +            self._get_disease_descriptors(record)
I would consider doing the checks below after each descriptor, so that we aren't calling all normalizers if it's not needed.

2021-04-05 14:26 UTC, jsstevenson approved these changes

2021-04-19 14:42 UTC, jsstevenson approved these changes
🎉

2021-04-19 14:42 UTC, jsstevenson commented on metakb/harvesters/moalmanac.py
>              logger.info('MOAlamanc harvester was successful.')
```suggestion
            logger.info('MOAlmanac harvester was successful.')
```

2021-04-19 14:42 UTC, jsstevenson commented on metakb/harvesters/moalmanac.py
>              logger.info('MOAlamanc harvester was successful.')
(same typo on line 36)

2021-04-19 15:03 UTC, MayLiu27 commented on metakb/harvesters/moalmanac.py
>              logger.info('MOAlamanc harvester was successful.')
> (same typo on line 36)

good catch! Thanks.

2021-04-19 17:28 UTC, jsstevenson approved these changes

2021-05-03 13:27 UTC, jsstevenson approved these changes

2021-05-10 12:06 UTC, korikuzma commented
These changes are already merged into master. Can we close this? @MayLiu27

2021-05-10 13:26 UTC, closed without merging